### ISSUE TITLE
[Request/Balancing]: Change the Level 1 SPH Length Restriction to 9.0m, and the Height to 6.0m

### ISSUE THREAD

**Issue by MystLeissa** [zer0Kerbal/Komplexity#39]
### Description of the new feature / enhancement

Allow Level 1 SPH to build planes. (I think you accidentally copied the height/length restrictions from the VAB, so it reads 9.0 Height and 6.0 Length - which is nearly impossible to construct a plane in (The Tails required for stability come to 6m on their own, not including other parts.)

### Proposed technical implementation details

Simple Swap of Height and Length Values.

**Comment by zer0Kerbal** [comment]
*sheepish grin* I don't have all that much experience with the runway except crashing into it.

Thank you @MystLeissa

 just level 1? or

**Comment by zer0Kerbal** [comment]
Sizes for the launchpad are easy - L x W x H

so you are suggesting size = 9,6,6 - I have no issues with that - once I remember which is what, will swap them all)

```			size = 6, 9, 6
			size = 15, 18, 15
			size = 20, 36, 23
			size = 30, 72, 28
			size = 45, 80, 33
			size = 75, 100, 38
			size = 100, 120, 45
			size = 125, 140, 49
			size = 150, 160, 54
			size = -1, -1, -1```

**Comment by zer0Kerbal** [comment]
research:

Stock default for both Runway and Launchpad is
```
		craftSizeLimit
		{
			size = 15, 20, 15
			size = 28, 36, 28
			size = -1, -1, -1
		}
```
![image](https://user-images.githubusercontent.com/39887717/163516438-8d8ad49c-7511-41dd-baf5-77db267b77f7.png)

now that we can correlate which slot in the array goes to which dimension

**Comment by zer0Kerbal** [comment]
How's this @MystLeissa ? 👁️‍🗨️ 🔍 
```
		craftSizeLimit
		{
			// width, height, length
			size = 6, 6, 9
			size = 15, 15, 18
			size = 20, 23, 36
			size = 30, 28, 72
			size = 45, 33, 80
			size = 75, 38, 100
			size = 100, 45, 120
			size = 125, 49, 140
			size = 150, 54, 160
			size = -1, -1, -1
```

**Comment by zer0Kerbal** [comment]
looks like need to swap the launchpad as well:
![engineeringReport-VAB](https://user-images.githubusercontent.com/39887717/163519231-e0d6c359-9263-43ee-af13-f3d1f2712b95.png)

**Comment by zer0Kerbal** [comment]
@MystLeissa Would you kindly try this and see if it corrects this issue for you? Of course, please tell me here. Thank you!

Place it here `<KSP_ROOT>/GameData/KGEx/Komplexity/Configs/`
[Runway.zip](https://github.com/zer0Kerbal/Komplexity/files/8494040/Runway.zip)

**Comment by MystLeissa** [comment]
Downloading the Test Patch now - I'll let you know in about 5 minutes.

**Comment by MystLeissa** [comment]
Ok So I have a little more feedback: Assuming your using a modified Fighter Design (Which I'm using Firespitter, which in general is SMALLER than the Vanilla Jets, but tends to have more parts), A Flyable Plane, needs ~0.5m extra on the width (for wingspan), beyond that it fixed the problem. For Reference I have included a picture of the plane I am attempting to use as a "Bare Minimal":
![20220415175741_1](https://user-images.githubusercontent.com/28554657/163638316-53e51adc-8611-46cf-96b8-947f738e761d.jpg)

**Comment by MystLeissa** [comment]
ok I solved the problem by changing the Array's First Level to 7w instead of the 6w you had, so I think that should work. I manually install so that's probably why the KGEx Folder didn't matter (plus my last update was prerelease so it's been some time), but yeah I think that's got it. it's not a perfect match for the launchpad, but then it doesn't need to be in my honest opinion, Planes are very different shapes from rockets.

**Comment by zer0Kerbal** [comment]
excellent. been ruminating over the numbers - and they go up way to fast imho.

**Comment by zer0Kerbal** [comment]
proposed:
```
			// wingspan(width), height, length
			size = 7, 6, 9
			size = 12, 12, 18
			size = 17, 17, 24
			size = 25, 24, 30
			size = 36, 31, 50
			size = 48, 39, 76
			size = 61, 48, 111
			size = 75, 68, 124
			size = 90, 88, 149
			size = -1, -1, -1
```

currently 
```
// wingspan(width), height, length
			size = 6, 6, 9
			size = 12, 12, 18
			size = 24, 24, 36
			size = 48, 48, 72
			size = 72, 72, 100
			size = 96, 96, 120
			size = 100, 100, 130
			size = 125, 125, 140
			size = 150, 150, 172
			size = -1, -1, -1
```

**Comment by zer0Kerbal** [comment]
@MystLeissa thank you - here is an updated version. Kindly, same thing.

[Runway.zip](https://github.com/zer0Kerbal/Komplexity/files/8499113/Runway.zip)
