### ISSUE TITLE
[Bug 🐞]: JX2Antenna+OPM Incompatibility

### ISSUE THREAD

**Issue by Ictiv** [zer0Kerbal/Komplexity#48]
### Brief description of your issue

When both JX2Antenna and Outer Planets Mod is installed, a patch file from JX2Antenna overrides another patch from OPM that adjusts the Tracking Station building's stats, resulting in either one or both erasing Komplexity's changes.

### Steps to reproduce

Install Komplexity, JX2Antenna and OPM, start a new game (or load old one, but I suspect it could potentially corrupt save so not advised). View the upgrade cost of tracking station upon starting a new Career game, or check the level of the tracking station in a new Sandbox game.

### Expected behavior

In case of Career, cost should be the 15k cost default to Komplexity to upgrade. Can upgrade 9 times at Komplexity costs.
In case of Sandbox, building should be maxed out at level 10.

### Actual behavior

In case of Career, cost is 150k cost default to Komplexity to upgrade. Can only upgrade twice.
(Untested, but fairly certain:) In case of Sandbox, building is maxed out at level 3.
[MMPatch.zip](https://github.com/zer0Kerbal/Komplexity/files/9125034/MMPatch.zip)

Additional note regarding the contents of the .zip: As since I had "patched" the issue by deleting the offending files on my end and restarted, I don't have all my logs (KSP's, and both Module Manager) logs anymore. However, I did manage to keep the MMPatch.log file by forgetting to close Notepad from my searching, and it does show the order of the patches, so it should be sufficient. Can reproduce all three relevant log files on request by simply "un-patching" my installation.
The "patching" was my removing of both OPM's Patches/OPM_CommNet.cfg and JX2's Patches/jx2_OPM.cfg files from my own installation. After that, normal Komplexity behaviour returned.

### Environment

```shell
Komplexity Version: 1.0.0.0
OPM Version: 2:2.2.10
JX2Antenna Version: 2.0.5
KSP Version: 1.12.3.3173
Download/Installation: CKAN for mods, Steam for KSP.
```

### How did you download and install this?

CKAN (auto install with dependencies)

**Comment by zer0Kerbal** [comment]
Thank you @ictiv!

**Comment by Ictiv** [comment]
Ah, meant to note. You probably wouldn't notice this, but there is only abnormality that you couldn't reporoduce on your end even if you got the same mod list as me. Namely, I deleted a file from Kerbinside, which spawned half an extension of the Runway model, so it plays nicer with KSC Extended without me having to manually move stuff around. If you try to recreate my goliath modlist for whatever reason, there's probably going to be an extra line or two in there that is missing in the MMPatch.log I uploaded above because of that.
Oh, and my personal installation is also missing the Coronavirus features of SSTO, but that should be it.
Probably not relevant, but it doesn't hurt to throw it out there in case anyone ends up deep diving in that file.

**Comment by zer0Kerbal** [comment]
https://github.com/zer0Kerbal/Komplexity/issues/49

**Comment by zer0Kerbal** [comment]
#50

**Comment by zer0Kerbal** [comment]
https://github.com/KSPSnark/JX2Antenna/blob/master/files/Patches/jx2_OPM.cfg
